import { QuotePage } from "@/components/quotes/QuotePage";
import type { PublicQuote } from "@/lib/quotes/types";

export const metadata = {
  title: "Demo Angebot - NEONTRIP",
  robots: { index: false, follow: false },
};

const demoQuote: PublicQuote = {
  id: "demo-quote-id",
  request_id: "AN-11965",
  customer_id: null,
  trello_card_id: "demo-card",
  status: "draft",
  customer_email: "leon.heidemann@example.com",
  customer_name: "Leon Heidemann",
  company: "Schach zu Dritt",
  country: "Deutschland",
  currency: "EUR",
  share_token: "demo",
  created_at: new Date().toISOString(),
  subtotal_net: null,
  tax_amount: null,
  total_gross: null,
  items: [
    {
      id: "demo-product-1",
      section: "products",
      name: "LED-Leuchtschild inkl. 25% Rabatt Design #1",
      description:
        "Größe: 75x50cm\nLeuchtfarbe: Kaltweiß\nRückplatte: Formzuschnitt\nEinsatzbereich: Innen",
      quantity: 1,
      unit_price: 645,
      tax_rate: 19,
      optional: true,
      selected_default: true,
      quantity_editable: true,
      sort_order: 10,
    },
    {
      id: "demo-product-2",
      section: "products",
      name: "LED-Leuchtschild inkl. 25% Rabatt Design #2",
      description:
        "Größe: 100x60cm\nLeuchtfarbe: Warmweiß\nRückplatte: Acryl klar\nEinsatzbereich: Innen",
      quantity: 1,
      unit_price: 790,
      tax_rate: 19,
      optional: true,
      selected_default: true,
      quantity_editable: true,
      sort_order: 20,
    },
    {
      id: "demo-addon-dimmer",
      section: "addons",
      name: "Dimmer & Fernbedienung",
      description: "Stufenlose Helligkeitssteuerung für Ihr Leuchtschild.",
      quantity: 1,
      unit_price: 45,
      tax_rate: 19,
      optional: true,
      selected_default: false,
      quantity_editable: false,
      sort_order: 100,
    },
    {
      id: "demo-addon-rgb",
      section: "addons",
      name: "RGB-Option",
      description: "Mehrfarbige LED-Option mit Steuerung statt einfarbiger Beleuchtung.",
      quantity: 1,
      unit_price: 125,
      tax_rate: 19,
      optional: true,
      selected_default: false,
      quantity_editable: false,
      sort_order: 110,
    },
    {
      id: "demo-addon-wall",
      section: "addons",
      name: "Wandmontage-Set",
      description: "Befestigungsmaterial und Abstandshalter für eine saubere Montage.",
      quantity: 1,
      unit_price: 35,
      tax_rate: 19,
      optional: true,
      selected_default: true,
      quantity_editable: false,
      sort_order: 120,
    },
    {
      id: "demo-shipping-standard",
      section: "shipping",
      name: "Standard-Versand",
      description: "Versicherter Standardversand nach Fertigstellung.",
      quantity: 1,
      unit_price: 0,
      tax_rate: 19,
      optional: true,
      selected_default: true,
      quantity_editable: false,
      sort_order: 300,
    },
    {
      id: "demo-shipping-express",
      section: "shipping",
      name: "Express-Versand",
      description: "Schnellere Versandabwicklung nach Produktionsabschluss.",
      quantity: 1,
      unit_price: 90,
      tax_rate: 19,
      optional: true,
      selected_default: false,
      quantity_editable: false,
      sort_order: 310,
    },
  ],
  images: [
    {
      id: "demo-image-1",
      storage_url: "/quote-demo/mockup-01.webp",
      label: "Mockup01",
      sort_order: 10,
    },
    {
      id: "demo-image-2",
      storage_url: "/quote-demo/mockup-02.webp",
      label: "Mockup02",
      sort_order: 20,
    },
  ],
};

export default function DemoQuotePage() {
  return <QuotePage quote={demoQuote} />;
}
