import fs from 'node:fs';import * as S from './collective.mjs';
const dir=process.argv[2];if(!dir)throw new Error('snapshot directory required');
const original=JSON.parse(fs.readFileSync(dir+'/qonto.before.json'));const projection=JSON.parse(fs.readFileSync(dir+'/projection.before.json'));
const q=structuredClone(original),p=structuredClone(projection);
const common=fs.readFileSync(new URL('./collective.mjs',import.meta.url),'utf8').split('export function references')[0];
const code=(names,tail)=>common+names.map(n=>S[n].toString()).join('\n')+'\n'+tail;
const node=(w,name,type,parameters,credentials,version=2)=>{const n={id:'t300-'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,type,typeVersion:version,position:[2200,400+w.nodes.length*35],parameters};if(credentials)n.credentials=credentials;w.nodes.push(n);return n;};
const connect=(w,a,b,index=0)=>{w.connections[a]??={main:[]};w.connections[a].main[index]=[{node:b,type:'main',index:0}];};
const http=(w,name,url,cred,ctype='httpHeaderAuth',extra={})=>node(w,name,'n8n-nodes-base.httpRequest',{method:'GET',url,authentication:'predefinedCredentialType',nodeCredentialType:ctype,options:{timeout:30000,response:{response:{fullResponse:true,responseFormat:'json'}}},...extra},cred,4.2);
const cod=(w,name,names,tail)=>node(w,name,'n8n-nodes-base.code',{mode:'runOnceForAllItems',jsCode:code(names,tail).replaceAll('}}','} }')});
const iff=(w,name,left)=>node(w,name,'n8n-nodes-base.if',{conditions:{options:{caseSensitive:true,leftValue:'',typeValidation:'strict',version:2},conditions:[{id:'t300-condition',leftValue:left,rightValue:true,operator:{type:'boolean',operation:'true',singleValue:true}}],combinator:'and'},options:{}});
const cred=name=>original.nodes.find(n=>n.name===name).credentials;
const shop=cred('Shopify: Find Order'),sb=cred('Check Already Processed'),eb=cred('easybill: Find Invoice');
cod(q,'Collective: Route',['references'],"return [{json:{...$input.first().json,collective:references($input.first().json.reference).length>1}}];");
iff(q,'Collective Payment?','={{ $json.collective }}');
node(q,'Collective: Read Bank','n8n-nodes-qonto.qonto',{authentication:'logKey',resource:'transactions',operation:'showTransaction',id:'={{ $json.transaction_id }}'},{qontoApi:{id:'I4RLhKqbP70giaTd',name:'Qonto account'}},2);
cod(q,'Collective: Verify Bank',['references','verifyBank'],"return [{json:verifyBank($input.first().json,$('Collective: Route').first().json)}];");
const fields='id legacyResourceId name createdAt cancelledAt displayFinancialStatus totalPriceSet{shopMoney{amount currencyCode} } currentTotalPriceSet{shopMoney{amount currencyCode} } totalOutstandingSet{shopMoney{amount currencyCode} } billingAddress{company firstName lastName} customer{id} ';
http(q,'Collective: Read Orders','https://galaxybuzzdk.myshopify.com/admin/api/2026-07/graphql.json',shop,'shopifyAccessTokenApi',{method:'POST',sendBody:true,specifyBody:'json',jsonBody:'={{ {query:'+JSON.stringify('query CollectiveOrders($search:String!){orders(first:50,query:$search){nodes{'+fields+'} pageInfo{hasNextPage} } }')+',variables:{search:$json.references.map(r=>\'name:"#\'+r+\'"\').join(\' OR \')}} }}'});
const qo=q.nodes.find(n=>n.name==='Collective: Read Orders');qo.parameters.jsonBody=qo.parameters.jsonBody.replace('}} }}','} } }}');
const select='id,shopify_order_id,shopify_order_name,customer,currency,total_gross_cents,status,tax_review_status,lock_version,paid_at,cancelled_at,refunded_at,final_invoice_at,current_revision,billing_payments(id),billing_documents(easybill_document_id,document_type,document_number,status,amount_cents,currency,revision)';
http(q,'Collective: Read Cases','={{ '+JSON.stringify('https://klibiejfisijpagzkxls.supabase.co/rest/v1/billing_cases?select='+select+'&shopify_order_name=in.')+' + encodeURIComponent(\'(\'+$(\'Collective: Verify Bank\').first().json.references.map(r=>\'#\'+r).join(\',\')+\')\') }}',sb);
cod(q,'Collective: Plan',['planGroup'],"return [{json:planGroup($('Collective: Verify Bank').first().json,$('Collective: Read Orders').first().json.body,$input.first().json.body)}];");
cod(q,'Collective: Documents',[],"return $input.first().json.documents.map(d=>({json:d}));");
http(q,'Collective: Read Easybill','={{ "https://api.easybill.de/rest/v1/documents/"+$json.id }}',eb);
cod(q,'Collective: Verify Easybill',['verifyDocuments'],"return [{json:verifyDocuments($('Collective: Plan').first().json,$input.all().map(i=>i.json.body))}];");
http(q,'Collective: Register Group','https://klibiejfisijpagzkxls.supabase.co/rest/v1/rpc/billing_collective_payment_ingest',sb,'httpHeaderAuth',{method:'POST',sendBody:true,specifyBody:'json',jsonBody:'={{ {p_payment:$json.payment,p_allocations:$json.allocations} }}'});
cod(q,'Collective: Verify Receipt',[],"const r=$input.first().json.body;const plan=$('Collective: Verify Easybill').first().json;if(r?.ok!==true||r.transactionId!==plan.payment.id||r.amountCents!==plan.payment.amountCents||!Array.isArray(r.payments)||r.payments.length!==plan.allocations.length||!plan.allocations.every(a=>r.payments.some(p=>p.orderId===a.orderId&&p.billingCaseId===a.caseId&&Number(p.amountCents)===a.amountCents&&p.matchStatus==='MATCHED')))throw new Error('COLLECTIVE_RECEIPT_INVALID');return [{json:{ok:true,transactionId:r.transactionId,allocations:r.payments.length,amountCents:r.amountCents,duplicate:r.duplicate}}];");
cod(q,'Collective: Review',[],"const c=$('Collective: Route').first().json;return [{json:{...c,sendEmail:true,stop:true,reason:'collective_payment_requires_review',emailSubject:'N8N Prüfen: Sammelzahlung '+c.neonNumber,emailBody:'Sammelzahlung konnte nicht sicher zugeordnet werden. Betrag: '+c.amount+' EUR. Zahler: '+c.customer_name+'. Verwendungszweck: '+c.reference+'. Qonto: '+c.transaction_id+'. Grund: '+String($json.error?.message||$json.message||'Validierung fehlgeschlagen')+'. Bereits registrierte Zahlungsanteile niemals erneut manuell buchen; Billing-Zahlungsnachweise prüfen.'}}];");
const chain=['Collective: Route','Collective Payment?','Collective: Read Bank','Collective: Verify Bank','Collective: Read Orders','Collective: Read Cases','Collective: Plan','Collective: Documents','Collective: Read Easybill','Collective: Verify Easybill','Collective: Register Group','Collective: Verify Receipt'];
connect(q,'Not Duplicate?','Collective: Route');for(let i=0;i<chain.length-1;i++)connect(q,chain[i],chain[i+1]);connect(q,'Collective Payment?','Shopify: Find Order',1);connect(q,'Collective: Review','Send Error Email?');
for(const name of chain.slice(2)){const n=q.nodes.find(n=>n.name===name);n.onError='continueErrorOutput';connect(q,name,'Collective: Review',1);}
// Collective-only projection guards; all untagged jobs keep their existing route.
const ebread=http(p,'Collective: Read Invoice','={{ "https://api.easybill.de/rest/v1/documents/"+$("Normalize Projection Job").first().json.job.payload.documentId }}',eb);
http(p,'Collective: Read Invoice Payments','={{ "https://api.easybill.de/rest/v1/document-payments?limit=100&page=1&document_id="+$("Normalize Projection Job").first().json.job.payload.documentId }}',eb);
cod(p,'Collective: Decide Easybill',['easybillDecision'],"return [{json:easybillDecision($('Normalize Projection Job').first().json,$('Collective: Read Invoice').first().json.body,$input.first().json.body)}];");
iff(p,'Collective Easybill?','={{ !!$json.job.payload.collectivePaymentId }}');
iff(p,'Collective Easybill Payment Needed?','={{ $json.alreadyDone === false }}');
connect(p,'Easybill Payment','Collective Easybill?');
connect(p,'Collective Easybill?','Collective: Read Invoice');connect(p,'Collective Easybill?','Easybill Record Payment',1);
connect(p,'Collective: Read Invoice','Collective: Read Invoice Payments');connect(p,'Collective: Read Invoice Payments','Collective: Decide Easybill');connect(p,'Collective: Decide Easybill','Collective Easybill Payment Needed?');
connect(p,'Collective Easybill Payment Needed?','Easybill Record Payment');connect(p,'Collective Easybill Payment Needed?','Prepare Projection Success',1);
for(const name of ['Collective: Read Invoice','Collective: Read Invoice Payments','Collective: Decide Easybill']){p.nodes.find(n=>n.name===name).onError='continueErrorOutput';connect(p,name,'Prepare Projection Failure',1);}
const sn=p.nodes.find(n=>n.name==='Shopify Read Payment State');sn.parameters.jsonBody=sn.parameters.jsonBody.replace('id name canMarkAsPaid displayFinancialStatus','id name canMarkAsPaid displayFinancialStatus cancelledAt totalPriceSet{shopMoney{amount currencyCode} } currentTotalPriceSet{shopMoney{amount currencyCode} } totalOutstandingSet{shopMoney{amount currencyCode} }');
const mn=p.nodes.find(n=>n.name==='Shopify Mark Order Paid');mn.parameters.jsonBody=mn.parameters.jsonBody.replace('order { id displayFinancialStatus }','order { id displayFinancialStatus cancelledAt totalPriceSet { shopMoney { amount currencyCode } } currentTotalPriceSet { shopMoney { amount currencyCode } } totalOutstandingSet { shopMoney { amount currencyCode } } }');
const dn=p.nodes.find(n=>n.name==='Decide Shopify Payment');dn.parameters.jsCode=code(['shopifyDecision'],"const collectiveCtx=$('Normalize Projection Job').first().json;if(collectiveCtx.job.payload.collectivePaymentId)return [{json:shopifyDecision(collectiveCtx,$json.body??$json)}];\n"+dn.parameters.jsCode);
const success=p.nodes.find(n=>n.name==='Prepare Projection Success');success.parameters.jsCode=code(['projectionSuccess'],"const collectiveCtx=$('Normalize Projection Job').first().json;if(collectiveCtx.job.payload.collectivePaymentId)return [{json:projectionSuccess(collectiveCtx,$json.body??$json)}];\n"+success.parameters.jsCode);
const rec=p.nodes.find(n=>n.name==='Easybill Record Payment');rec.parameters.jsonBody=rec.parameters.jsonBody.replace("notice:$json.job.payload.markPaid===true?","notice:$json.job.payload.collectiveAllocationId?('Qonto allocation '+$json.job.payload.collectiveAllocationId):$json.job.payload.markPaid===true?");
for(const [name,w,before] of [['qonto',q,original],['projection',p,projection]]){
 const ops=[];for(const n of w.nodes){const old=before.nodes.find(o=>o.id===n.id);if(!old)ops.push({type:'addNode',node:n});else if(JSON.stringify(n)!==JSON.stringify(old))ops.push({type:'updateNode',nodeId:n.id,updates:{parameters:n.parameters}});}
 for(const [a,outputs]of Object.entries(w.connections)){if(JSON.stringify(outputs)!==JSON.stringify(before.connections[a])){if(before.connections[a])for(let i=0;i<before.connections[a].main.length;i++)for(const edge of before.connections[a].main[i])ops.push({type:'removeConnection',source:a,target:edge.node,sourceOutput:i,targetInput:edge.index});for(let i=0;i<outputs.main.length;i++)for(const edge of outputs.main[i]||[])ops.push({type:'addConnection',source:a,target:edge.node,sourceOutput:i,targetInput:edge.index});}}
 fs.writeFileSync(dir+'/'+name+'.after.json',JSON.stringify(w,null,2));
 fs.writeFileSync(new URL('./'+name+'.patch.json',import.meta.url),JSON.stringify({id:w.id,operations:ops},null,2));
 console.log(name,JSON.stringify({beforeNodes:before.nodes.length,afterNodes:w.nodes.length,changedExisting:w.nodes.filter(n=>before.nodes.some(b=>b.id===n.id&&JSON.stringify(b)!==JSON.stringify(n))).map(n=>n.name),operations:ops.length}));
}
