"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,ExternalLink,MailCheck,RefreshCcw } from "lucide-react";
import { OpsLoginCard } from "../ops-login-card";
import { OpsPageHeader } from "../ops-page-header";
import { OpsPageIntro,opsPageContainerClass,opsPageShellClass } from "../ops-design";
type Organization={id:string;name:string;canonicalDomain:string;countryCode:string|null;research:Record<string,unknown>};
type Delivery={id:string;organization_id:string;recipient_email:string;status:string;attempt_count:number;sent_at:string|null;alert_status:string;last_error_summary:string|null};
type Offer={id:string;organization_id:string;currency:string|null;unit_price:number|null;total_price:number|null;shipping_cost:number|null;production_days_min:number|null;production_days_max:number|null;shipping_days_min:number|null;shipping_days_max:number|null;valid_until:string|null;confidence:number|null;review_status:string};
type Reply={id:string;organization_id:string|null;sender_email:string;received_at:string;match_status:string;extraction_status:string};
type RequestItem={id:string;trello_card_url:string;trello_card_name:string;status:string;selected_organization_id:string|null;selected_by:string|null;created_at:string;deliveries:Delivery[];offers:Offer[];replies:Reply[]};
type Board={organizations:Organization[];items:RequestItem[]};
function money(value:number|null,currency:string|null){return value===null?"–":new Intl.NumberFormat("de-DE",{style:"currency",currency:currency||"EUR"}).format(value);}
function days(min:number|null,max:number|null){if(min===null&&max===null)return"–";return min===max?`${min} Tage`:`${min??"?"}–${max??"?"} Tage`;}
function date(value:string|null){return value?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"–";}
function tone(status:string){if(["sent","validated","verified","selected"].includes(status))return"bg-emerald-50 text-emerald-800 border-emerald-200";if(["failed","unmatched"].includes(status))return"bg-rose-50 text-rose-800 border-rose-200";return"bg-amber-50 text-amber-800 border-amber-200";}
export function EuSupplierQuotesClient({initialHasSession,opsEnabled,localMode}:{initialHasSession:boolean;opsEnabled:boolean;localMode:boolean}){
 const[hasSession,setHasSession]=useState(initialHasSession),[operatorName,setOperatorName]=useState(""),[password,setPassword]=useState(""),[board,setBoard]=useState<Board|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false),[query,setQuery]=useState("");
 useEffect(()=>{try{setOperatorName(localStorage.getItem("neontrip-eu-supplier-operator")||"");}catch{}},[]);
 async function login(){const response=await fetch("/api/ops/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:password})});if(response.ok)setHasSession(true);else setError("Ops-Login fehlgeschlagen.");}
 async function load(){setLoading(true);setError(null);try{const response=await fetch("/api/ops/eu-supplier-quotes",{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"Daten konnten nicht geladen werden.");setBoard(payload.board);}catch(cause){setError(cause instanceof Error?cause.message:"Unbekannter Fehler");}finally{setLoading(false);}}
 useEffect(()=>{if(hasSession||localMode)void load();},[hasSession,localMode]);
 async function select(requestId:string,organizationId:string){if(!operatorName.trim()){setError("Bitte zuerst deinen Namen eintragen.");return;}if(!window.confirm("Diesen Supplier auswählen? Es wird noch keine E-Mail versendet."))return;localStorage.setItem("neontrip-eu-supplier-operator",operatorName);const response=await fetch("/api/ops/eu-supplier-quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"select_organization",requestId,organizationId,operatorName})});if(!response.ok){const payload=await response.json();setError(payload.error||"Auswahl fehlgeschlagen.");return;}await load();}
 const items=useMemo(()=>board?.items.filter((item)=>item.trello_card_name.toLowerCase().includes(query.toLowerCase()))||[],[board,query]);
 if(opsEnabled&&!localMode&&!hasSession)return <OpsLoginCard eyebrow="NEONTRIP Ops" title="EU Supplier 3D Schilder" description="Interner Angebotsvergleich." activeApp="euSupplierQuotes" operatorName={operatorName} password={password} error={error} buttonLabel="Einloggen" onOperatorNameChange={setOperatorName} onPasswordChange={setPassword} onSubmit={login}/>;
 return <main className={opsPageShellClass}><div className={opsPageContainerClass}><OpsPageHeader active="euSupplierQuotes" label="EU Supplier 3D Schilder"/><OpsPageIntro eyebrow="Beschaffung" title="Supplier-Angebote vergleichen" description="Trello-Anfragen, bestätigte Zustellung, Antworten, Preise sowie Produktions- und Versandzeiten."/>
 <section className="grid gap-3 rounded-xl border border-stone-200 bg-white p-4 md:grid-cols-[1fr_18rem_auto]"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Trello-Anfrage suchen" className="rounded-lg border border-stone-300 px-3 py-2"/><input value={operatorName} onChange={(event)=>setOperatorName(event.target.value)} placeholder="Dein Name für Auswahl" className="rounded-lg border border-stone-300 px-3 py-2"/><button onClick={()=>void load()} className="flex items-center justify-center gap-2 rounded-lg bg-stone-950 px-4 py-2 text-white"><RefreshCcw className="h-4 w-4"/>{loading?"Lädt…":"Aktualisieren"}</button></section>
 {error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-900">{error}</div>:null}<div className="grid gap-5">{items.map((request)=><section key={request.id} className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-stone-200 p-5"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold">{request.trello_card_name}</h2><span className={`rounded-full border px-2 py-1 text-xs ${tone(request.status)}`}>{request.status}</span></div><p className="mt-1 text-sm text-stone-500">Anfrage vom {date(request.created_at)}</p></div><a href={request.trello_card_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-sm font-medium">Trello-Karte <ExternalLink className="h-4 w-4"/></a></header>
 <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="p-3">Supplier</th><th className="p-3">E-Mail</th><th className="p-3">Antwort</th><th className="p-3">Preis</th><th className="p-3">Versandkosten</th><th className="p-3">Produktion</th><th className="p-3">Versand</th><th className="p-3">Aktion</th></tr></thead><tbody>{board?.organizations.map((org)=>{const delivery=request.deliveries.find((item)=>item.organization_id===org.id),offer=request.offers.find((item)=>item.organization_id===org.id),reply=request.replies.find((item)=>item.organization_id===org.id);return <tr key={org.id} className={`border-t border-stone-100 ${request.selected_organization_id===org.id?"bg-emerald-50/60":""}`}><td className="p-3"><p className="font-semibold">{org.name}</p><p className="text-xs text-stone-500">@{org.canonicalDomain}</p></td><td className="p-3"><span className={`inline-flex rounded-full border px-2 py-1 text-xs ${tone(delivery?.status||"queued")}`}>{delivery?.status||"nicht angelegt"}</span><p className="mt-1 text-xs text-stone-500">{delivery?.sent_at?date(delivery.sent_at):delivery?.last_error_summary||""}</p></td><td className="p-3">{reply?<><p>{date(reply.received_at)}</p><p className="text-xs text-stone-500">{reply.sender_email}</p></>:<span className="text-stone-400">ausstehend</span>}</td><td className="p-3 font-semibold">{money(offer?.total_price??offer?.unit_price??null,offer?.currency||null)}</td><td className="p-3">{money(offer?.shipping_cost??null,offer?.currency||null)}</td><td className="p-3">{days(offer?.production_days_min??null,offer?.production_days_max??null)}</td><td className="p-3">{days(offer?.shipping_days_min??null,offer?.shipping_days_max??null)}</td><td className="p-3"><button disabled={!offer||request.selected_organization_id===org.id} onClick={()=>void select(request.id,org.id)} className="rounded-lg bg-stone-950 px-3 py-2 text-xs font-semibold text-white disabled:bg-stone-300">{request.selected_organization_id===org.id?"Ausgewählt":"Von euch bestellen"}</button></td></tr>})}</tbody></table></div>
 {request.deliveries.some((item)=>item.status==="failed")?<div className="flex gap-2 border-t border-rose-200 bg-rose-50 p-3 text-sm text-rose-900"><AlertTriangle className="h-4 w-4"/>Supplier-Mail endgültig fehlgeschlagen. Warnstatus: {request.deliveries.filter((item)=>item.status==="failed").map((item)=>item.alert_status).join(", ")}</div>:null}</section>)}</div>
 {!loading&&!items.length?<div className="rounded-xl border border-dashed border-stone-300 p-10 text-center text-stone-500"><MailCheck className="mx-auto mb-3 h-7 w-7"/>Noch keine passenden Supplier-Anfragen.</div>:null}</div></main>;
}
