import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const read = (file: string) => fs.readFileSync(path.join(process.cwd(), file), "utf8");

test("Ops exposes a dedicated NEONTRIP billing department", () => {
  const switcher = read("src/app/ops/ops-app-switcher.tsx");
  const client = read("src/app/ops/rechnungen/page-client.tsx");
  assert.match(switcher, /label: "Rechnungen"/);
  assert.match(switcher, /href: "\/ops\/rechnungen"/);
  assert.match(client, /Pro-forma, Rechnungen und Korrekturen/);
  assert.match(client, /active="billing"/);
  assert.match(client, /Rechnung · \{days\} Tage/);
  assert.match(client, /Neue Pro-forma-Version/);
  assert.match(client, /Zahlung eingegangen/);
  assert.match(client, /Zugestellt/);
  assert.match(client, /Rechnung jetzt erstellen/);
  assert.match(client, /Audit-Log protokolliert/);
  assert.match(client, /Rechnungs-E-Mail/);
  assert.match(client, /project_number/);
  assert.match(client, /Daten ändern/);
  assert.match(client, /Annehmen/);
  assert.match(client, /Ablehnen/);
  assert.match(client, /Erst diese endgültige Entscheidung versendet genau eine E-Mail/);
  assert.match(client, /Zur Rechnungsübersicht/);
  assert.match(client, /id="billing-payment-method"/);
  assert.match(client, /subtotal_net_cents/);
  assert.match(client, /vat_cents/);
  assert.match(client, /Gesamtbetrag/);
  assert.match(client, /lg:grid-cols-\[minmax\(0,1fr\)_22rem\]/);
  assert.match(client, /Weitere interne Aktionen/);
  assert.match(client, /admin\.shopify\.com\/store\/galaxybuzzdk\/orders/);
  assert.match(client, /c496191\.easybill\.de/);
  assert.match(client, /Aktueller Easybill-Beleg/);
});

test("customer portal is invoice-only and becomes read-only after final invoice", () => {
  const portal = read("src/app/rechnung/[token]/portal-client.tsx");
  const middleware = read("src/middleware.ts");
  const repository = read("src/lib/ops/billing/repository.ts");
  assert.match(portal, /Rechnungsdaten bearbeiten/);
  assert.match(portal, /Speichern und zur Prüfung senden/);
  assert.match(portal, /readOnly=\{!editing\}/);
  assert.match(portal, /nicht verändert/);
  assert.match(portal, /Änderungen sind nicht mehr möglich/);
  assert.match(portal, /Live-Vorschau/);
  assert.match(portal, /Nettobetrag/);
  assert.match(portal, /Umsatzsteuer/);
  assert.match(portal, /Gesamtbetrag/);
  assert.match(portal, /Bestellung \{billing\.shopify_order_name\}/);
  assert.match(portal, /Zahlung ausstehend/);
  assert.match(portal, /Das Lieferland ist für die steuerliche Behandlung maßgeblich/);
  assert.match(portal, /USt-ID prüfen/);
  assert.match(portal, /vatCheck\.status === "valid"/);
  assert.match(portal, /Die USt-IdNr\. wurde beim EU-Dienst bestätigt/);
  assert.match(portal, /USt-ID geprüft · Reverse Charge/);
  assert.match(portal, /USt-ID geprüft · Freigabe ausstehend/);
  assert.match(portal, /deliveryAddress/);
  assert.match(portal, /delivery\.contactCompany/);
  assert.match(portal, /firstName: form\.deliveryFirstName/);
  assert.match(portal, /lastName: form\.deliveryLastName/);
  assert.match(portal, /deliveryInstructions/);
  assert.match(portal, /firstNonEmptyText\(requested\.invoiceEmail, billing\.invoiceEmail, billing\.customer_email/);
  assert.match(repository, /invoiceEmail:\s*[\s\S]*billingCase\.customer_email/);
  assert.match(portal, /Wird nach Freigabe direkt in Shopify übernommen/);
  assert.match(portal, /pendingChanges\(payload\)/);
  assert.match(portal, /requested\.vatValidation \|\| payload\.billingCase\.vat_validation/);
  assert.doesNotMatch(portal, /const hasVatId = form\.vatId\.trim\(\)\.length > 0/);
  assert.match(middleware, /rechnung\.neontrip\.de/);
  assert.doesNotMatch(portal, /Kauf auf Rechnung anfragen/);
  assert.match(portal, /PDF öffnen/);
  assert.match(portal, /Projektnummer \(optional\)/);
  assert.match(portal, /projectNumber/);
  const download = read("src/app/api/rechnung/[token]/documents/[documentId]/route.ts");
  assert.match(download, /getBillingPortalDocument/);
  assert.match(download, /Content-Disposition/);
  assert.match(download, /easybill\.de\/rest\/v1\/documents/);
  assert.match(repository, /selectCurrentBillingDocuments/);
  assert.match(repository, /id,status,requested_changes,created_at,reviewed_at/);
  assert.doesNotMatch(repository, /id: `eq\.\$\{documentId\}`/);
});
