create table if not exists public.email_agent_mail_sync_state (
  mailbox_key text primary key,
  folder_name text not null default 'sentitems',
  cursor_url text,
  cursor_kind text not null default 'initial',
  initial_since timestamptz not null default (now() - interval '14 days'),
  next_retry_at timestamptz,
  lease_owner text,
  lease_until timestamptz,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  consecutive_errors integer not null default 0,
  last_http_status integer,
  last_error_code text,
  last_error_message text,
  last_correlation_id text,
  last_execution_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint email_agent_mail_sync_state_mailbox_key_check
    check (char_length(mailbox_key) between 3 and 320),
  constraint email_agent_mail_sync_state_folder_name_check
    check (folder_name in ('sentitems')),
  constraint email_agent_mail_sync_state_cursor_kind_check
    check (cursor_kind in ('initial', 'next', 'delta')),
  constraint email_agent_mail_sync_state_consecutive_errors_check
    check (consecutive_errors between 0 and 100000)
);

create table if not exists public.email_agent_sent_index (
  id bigint generated by default as identity primary key,
  mailbox_key text not null references public.email_agent_mail_sync_state(mailbox_key) on delete cascade,
  graph_message_id text not null,
  internet_message_id text,
  conversation_id text not null,
  sent_at timestamptz not null,
  received_at timestamptz,
  subject text,
  recipient_emails text[] not null default '{}'::text[],
  response_body_text text not null default '',
  response_body_hash text,
  sync_correlation_id text not null,
  matched_source_message_id text,
  matched_feedback_id bigint references public.email_agent_feedback(id) on delete set null,
  matched_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint email_agent_sent_index_graph_message_id_check
    check (char_length(graph_message_id) between 1 and 2000),
  constraint email_agent_sent_index_conversation_id_check
    check (char_length(conversation_id) between 1 and 2000),
  constraint email_agent_sent_index_body_length_check
    check (char_length(response_body_text) <= 6000),
  constraint email_agent_sent_index_message_unique
    unique (mailbox_key, graph_message_id)
);

create table if not exists public.email_agent_mail_sync_runs (
  correlation_id text primary key,
  mailbox_key text not null references public.email_agent_mail_sync_state(mailbox_key) on delete cascade,
  execution_id text not null,
  status text not null,
  request_kind text not null,
  http_status integer,
  message_count integer not null default 0,
  upserted_count integer not null default 0,
  cursor_kind text,
  retry_after_seconds integer,
  error_code text,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint email_agent_mail_sync_runs_status_check
    check (status in ('running', 'success', 'throttled', 'error', 'reset')),
  constraint email_agent_mail_sync_runs_request_kind_check
    check (request_kind in ('initial', 'next', 'delta')),
  constraint email_agent_mail_sync_runs_cursor_kind_check
    check (cursor_kind is null or cursor_kind in ('next', 'delta')),
  constraint email_agent_mail_sync_runs_counts_check
    check (message_count >= 0 and upserted_count >= 0),
  constraint email_agent_mail_sync_runs_execution_unique
    unique (mailbox_key, execution_id)
);

create index if not exists email_agent_sent_index_unmatched_conversation_idx
  on public.email_agent_sent_index (mailbox_key, conversation_id, sent_at)
  where matched_source_message_id is null;

create index if not exists email_agent_sent_index_internet_message_idx
  on public.email_agent_sent_index (internet_message_id)
  where internet_message_id is not null;

create index if not exists email_agent_mail_sync_runs_recent_idx
  on public.email_agent_mail_sync_runs (mailbox_key, started_at desc);

alter table public.email_agent_mail_sync_state enable row level security;
alter table public.email_agent_sent_index enable row level security;
alter table public.email_agent_mail_sync_runs enable row level security;

revoke all on table public.email_agent_mail_sync_state from public, anon, authenticated, service_role;
revoke all on table public.email_agent_sent_index from public, anon, authenticated, service_role;
revoke all on table public.email_agent_mail_sync_runs from public, anon, authenticated, service_role;

grant select, insert, update, delete on table public.email_agent_mail_sync_state to service_role;
grant select, insert, update, delete on table public.email_agent_sent_index to service_role;
grant select, insert, update, delete on table public.email_agent_mail_sync_runs to service_role;
revoke all on sequence public.email_agent_sent_index_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.email_agent_sent_index_id_seq to service_role;

create or replace function public.begin_email_agent_sent_sync_v1(
  p_mailbox_key text,
  p_execution_id text
)
returns jsonb
language plpgsql
set search_path = public
as $function$
declare
  mailbox_value text := lower(left(btrim(coalesce(p_mailbox_key, '')), 320));
  execution_value text := left(btrim(coalesce(p_execution_id, '')), 200);
  correlation_value text;
  claimed_state public.email_agent_mail_sync_state%rowtype;
  current_state public.email_agent_mail_sync_state%rowtype;
  skip_reason text;
begin
  if mailbox_value = '' or position('@' in mailbox_value) = 0 then
    raise exception 'valid mailbox_key is required';
  end if;
  if execution_value = '' then
    raise exception 'execution_id is required';
  end if;

  correlation_value := 'email-sent-delta:' || execution_value;

  insert into public.email_agent_mail_sync_state (mailbox_key)
  values (mailbox_value)
  on conflict (mailbox_key) do nothing;

  select *
  into current_state
  from public.email_agent_mail_sync_state
  where mailbox_key = mailbox_value;

  if current_state.lease_owner = execution_value
    and current_state.lease_until > now()
    and current_state.last_execution_id = execution_value
    and current_state.last_correlation_id = correlation_value then
    return jsonb_build_object(
      'version', 'email-sent-delta-request-v1',
      'should_request', true,
      'replayed', true,
      'mailbox_key', mailbox_value,
      'execution_id', execution_value,
      'correlation_id', correlation_value,
      'folder_name', current_state.folder_name,
      'cursor_url', current_state.cursor_url,
      'cursor_kind', current_state.cursor_kind,
      'initial_since', current_state.initial_since,
      'lease_until', current_state.lease_until
    );
  end if;

  update public.email_agent_mail_sync_state
  set lease_owner = execution_value,
      lease_until = now() + interval '2 minutes',
      last_attempt_at = now(),
      last_correlation_id = correlation_value,
      last_execution_id = execution_value,
      updated_at = now()
  where mailbox_key = mailbox_value
    and (lease_until is null or lease_until <= now())
    and (next_retry_at is null or next_retry_at <= now())
  returning * into claimed_state;

  if found then
    insert into public.email_agent_mail_sync_runs (
      correlation_id,
      mailbox_key,
      execution_id,
      status,
      request_kind
    ) values (
      correlation_value,
      mailbox_value,
      execution_value,
      'running',
      claimed_state.cursor_kind
    )
    on conflict (correlation_id) do update
    set status = 'running',
        request_kind = excluded.request_kind,
        http_status = null,
        message_count = 0,
        upserted_count = 0,
        cursor_kind = null,
        retry_after_seconds = null,
        error_code = null,
        error_message = null,
        completed_at = null,
        started_at = now();

    return jsonb_build_object(
      'version', 'email-sent-delta-request-v1',
      'should_request', true,
      'mailbox_key', mailbox_value,
      'execution_id', execution_value,
      'correlation_id', correlation_value,
      'folder_name', claimed_state.folder_name,
      'cursor_url', claimed_state.cursor_url,
      'cursor_kind', claimed_state.cursor_kind,
      'initial_since', claimed_state.initial_since,
      'lease_until', claimed_state.lease_until
    );
  end if;

  select *
  into current_state
  from public.email_agent_mail_sync_state
  where mailbox_key = mailbox_value;

  skip_reason := case
    when current_state.next_retry_at is not null and current_state.next_retry_at > now()
      then 'backoff'
    else 'leased'
  end;

  return jsonb_build_object(
    'version', 'email-sent-delta-request-v1',
    'should_request', false,
    'reason', skip_reason,
    'mailbox_key', mailbox_value,
    'execution_id', execution_value,
    'next_retry_at', current_state.next_retry_at,
    'lease_until', current_state.lease_until
  );
end;
$function$;

create or replace function public.record_email_agent_sent_sync_result_v1(
  p_mailbox_key text,
  p_execution_id text,
  p_correlation_id text,
  p_http_status integer,
  p_retry_after_seconds integer,
  p_cursor_url text,
  p_cursor_kind text,
  p_messages jsonb,
  p_error_code text,
  p_error_message text,
  p_reset_cursor boolean default false
)
returns jsonb
language plpgsql
set search_path = public
as $function$
declare
  mailbox_value text := lower(left(btrim(coalesce(p_mailbox_key, '')), 320));
  execution_value text := left(btrim(coalesce(p_execution_id, '')), 200);
  correlation_value text := left(btrim(coalesce(p_correlation_id, '')), 300);
  http_status_value integer := coalesce(p_http_status, 0);
  retry_seconds integer;
  current_errors integer := 0;
  message_item jsonb;
  graph_message_value text;
  conversation_value text;
  sent_at_value timestamptz;
  received_at_value timestamptz;
  recipient_values text[];
  processed_message_count integer := 0;
  stored_message_count integer := 0;
  run_status text;
  completed_run public.email_agent_mail_sync_runs%rowtype;
begin
  if mailbox_value = '' or execution_value = '' or correlation_value = '' then
    raise exception 'mailbox_key, execution_id and correlation_id are required';
  end if;

  if not exists (
    select 1
    from public.email_agent_mail_sync_state
    where mailbox_key = mailbox_value
      and lease_owner = execution_value
      and last_correlation_id = correlation_value
      and lease_until > now()
  ) then
    select *
    into completed_run
    from public.email_agent_mail_sync_runs
    where correlation_id = correlation_value
      and mailbox_key = mailbox_value
      and execution_id = execution_value
      and status in ('success', 'throttled', 'error', 'reset')
      and completed_at is not null;

    if found then
      return jsonb_build_object(
        'recorded', true,
        'replayed', true,
        'status', completed_run.status,
        'mailbox_key', completed_run.mailbox_key,
        'correlation_id', completed_run.correlation_id,
        'http_status', completed_run.http_status,
        'message_count', completed_run.message_count,
        'upserted_count', completed_run.upserted_count,
        'cursor_kind', completed_run.cursor_kind,
        'retry_after_seconds', completed_run.retry_after_seconds
      );
    end if;

    raise exception 'sync lease is not owned by this execution';
  end if;

  select consecutive_errors
  into current_errors
  from public.email_agent_mail_sync_state
  where mailbox_key = mailbox_value;

  if http_status_value between 200 and 299 then
    if coalesce(p_cursor_kind, '') not in ('next', 'delta') then
      raise exception 'successful Graph response requires next or delta cursor kind';
    end if;
    if coalesce(p_cursor_url, '') !~ '^https://graph[.]microsoft[.]com/v1[.]0/'
      or position('/messages/delta' in p_cursor_url) = 0 then
      raise exception 'invalid Microsoft Graph delta cursor URL';
    end if;
    if jsonb_typeof(coalesce(p_messages, '[]'::jsonb)) <> 'array' then
      raise exception 'messages must be a JSON array';
    end if;

    processed_message_count := jsonb_array_length(coalesce(p_messages, '[]'::jsonb));

    for message_item in
      select value
      from jsonb_array_elements(coalesce(p_messages, '[]'::jsonb))
    loop
      graph_message_value := left(btrim(coalesce(message_item->>'graph_message_id', '')), 2000);
      conversation_value := left(btrim(coalesce(message_item->>'conversation_id', '')), 2000);

      if graph_message_value = '' or conversation_value = '' then
        continue;
      end if;

      begin
        sent_at_value := nullif(message_item->>'sent_at', '')::timestamptz;
      exception when others then
        sent_at_value := null;
      end;
      if sent_at_value is null then
        continue;
      end if;

      begin
        received_at_value := nullif(message_item->>'received_at', '')::timestamptz;
      exception when others then
        received_at_value := null;
      end;

      select coalesce(array_agg(distinct lower(left(btrim(value), 320))), '{}'::text[])
      into recipient_values
      from jsonb_array_elements_text(
        case
          when jsonb_typeof(message_item->'recipient_emails') = 'array'
            then message_item->'recipient_emails'
          else '[]'::jsonb
        end
      )
      where btrim(value) <> '';

      insert into public.email_agent_sent_index (
        mailbox_key,
        graph_message_id,
        internet_message_id,
        conversation_id,
        sent_at,
        received_at,
        subject,
        recipient_emails,
        response_body_text,
        response_body_hash,
        sync_correlation_id
      ) values (
        mailbox_value,
        graph_message_value,
        left(nullif(btrim(coalesce(message_item->>'internet_message_id', '')), ''), 2000),
        conversation_value,
        sent_at_value,
        received_at_value,
        left(nullif(coalesce(message_item->>'subject', ''), ''), 1000),
        recipient_values,
        left(coalesce(message_item->>'response_body_text', ''), 6000),
        left(nullif(btrim(coalesce(message_item->>'response_body_hash', '')), ''), 200),
        correlation_value
      )
      on conflict (mailbox_key, graph_message_id) do update
      set internet_message_id = coalesce(excluded.internet_message_id, email_agent_sent_index.internet_message_id),
          conversation_id = excluded.conversation_id,
          sent_at = excluded.sent_at,
          received_at = coalesce(excluded.received_at, email_agent_sent_index.received_at),
          subject = coalesce(excluded.subject, email_agent_sent_index.subject),
          recipient_emails = excluded.recipient_emails,
          response_body_text = excluded.response_body_text,
          response_body_hash = coalesce(excluded.response_body_hash, email_agent_sent_index.response_body_hash),
          sync_correlation_id = excluded.sync_correlation_id,
          last_seen_at = now();

      stored_message_count := stored_message_count + 1;
    end loop;

    update public.email_agent_mail_sync_state
    set cursor_url = p_cursor_url,
        cursor_kind = p_cursor_kind,
        next_retry_at = null,
        lease_owner = null,
        lease_until = null,
        last_success_at = now(),
        consecutive_errors = 0,
        last_http_status = http_status_value,
        last_error_code = null,
        last_error_message = null,
        updated_at = now()
    where mailbox_key = mailbox_value;

    run_status := 'success';
    retry_seconds := null;
  elsif http_status_value = 429 then
    retry_seconds := greatest(30, least(3600, coalesce(p_retry_after_seconds, 300)));

    update public.email_agent_mail_sync_state
    set next_retry_at = now() + make_interval(secs => retry_seconds),
        lease_owner = null,
        lease_until = null,
        consecutive_errors = least(consecutive_errors + 1, 100000),
        last_http_status = http_status_value,
        last_error_code = left(nullif(btrim(coalesce(p_error_code, '')), ''), 200),
        last_error_message = left(nullif(btrim(coalesce(p_error_message, '')), ''), 2000),
        updated_at = now()
    where mailbox_key = mailbox_value;

    run_status := 'throttled';
  elsif coalesce(p_reset_cursor, false) or http_status_value in (404, 410) then
    retry_seconds := 300;

    update public.email_agent_mail_sync_state
    set cursor_url = null,
        cursor_kind = 'initial',
        initial_since = now() - interval '14 days',
        next_retry_at = now() + make_interval(secs => retry_seconds),
        lease_owner = null,
        lease_until = null,
        consecutive_errors = least(consecutive_errors + 1, 100000),
        last_http_status = http_status_value,
        last_error_code = left(nullif(btrim(coalesce(p_error_code, '')), ''), 200),
        last_error_message = left(nullif(btrim(coalesce(p_error_message, '')), ''), 2000),
        updated_at = now()
    where mailbox_key = mailbox_value;

    run_status := 'reset';
  else
    retry_seconds := least(
      3600,
      greatest(60, (60 * power(2, least(current_errors, 5)))::integer)
    );

    update public.email_agent_mail_sync_state
    set next_retry_at = now() + make_interval(secs => retry_seconds),
        lease_owner = null,
        lease_until = null,
        consecutive_errors = least(consecutive_errors + 1, 100000),
        last_http_status = http_status_value,
        last_error_code = left(nullif(btrim(coalesce(p_error_code, '')), ''), 200),
        last_error_message = left(nullif(btrim(coalesce(p_error_message, '')), ''), 2000),
        updated_at = now()
    where mailbox_key = mailbox_value;

    run_status := 'error';
  end if;

  update public.email_agent_mail_sync_runs
  set status = run_status,
      http_status = http_status_value,
      message_count = processed_message_count,
      upserted_count = stored_message_count,
      cursor_kind = case when run_status = 'success' then p_cursor_kind else null end,
      retry_after_seconds = retry_seconds,
      error_code = case when run_status = 'success' then null else left(nullif(btrim(coalesce(p_error_code, '')), ''), 200) end,
      error_message = case when run_status = 'success' then null else left(nullif(btrim(coalesce(p_error_message, '')), ''), 2000) end,
      completed_at = now()
  where correlation_id = correlation_value
    and mailbox_key = mailbox_value
    and execution_id = execution_value;

  return jsonb_build_object(
    'recorded', true,
    'status', run_status,
    'mailbox_key', mailbox_value,
    'correlation_id', correlation_value,
    'http_status', http_status_value,
    'message_count', processed_message_count,
    'upserted_count', stored_message_count,
    'cursor_kind', case when run_status = 'success' then p_cursor_kind else null end,
    'retry_after_seconds', retry_seconds
  );
end;
$function$;

create or replace function public.get_email_agent_feedback_candidates_v1(
  p_limit integer default 40
)
returns table (
  sent_index_id bigint,
  sent_graph_message_id text,
  sent_internet_message_id text,
  sent_conversation_id text,
  sent_at timestamptz,
  sent_recipient_emails text[],
  sent_body_text text,
  source_message_id text,
  conversation_id text,
  draft_id text,
  draft_body_hash text,
  draft_body_text text,
  draft_created_at timestamptz,
  from_email text,
  subject text,
  message_source text,
  risk_level text,
  reply_length_class text,
  context_snapshot jsonb
)
language sql
stable
set search_path = public
as $function$
  with pending as (
    select
      l.*,
      lead(l.created_at) over (
        partition by l.conversation_id
        order by l.created_at
      ) as next_draft_at
    from public.email_agent_log l
    where l.review_status = 'pending_review'
      and l.draft_created = true
      and l.request_id is not null
      and l.draft_body_text is not null
      and l.conversation_id is not null
      and l.created_at >= now() - interval '7 days'
  )
  select
    sent.id,
    sent.graph_message_id,
    sent.internet_message_id,
    sent.conversation_id,
    sent.sent_at,
    sent.recipient_emails,
    sent.response_body_text,
    pending.message_id,
    pending.conversation_id,
    pending.draft_id,
    pending.draft_body_hash,
    pending.draft_body_text,
    pending.created_at,
    pending.from_email,
    pending.subject,
    pending.message_source,
    pending.risk_level,
    pending.reply_length_class,
    pending.context_snapshot
  from pending
  join lateral (
    select s.*
    from public.email_agent_sent_index s
    where s.mailbox_key = 'support@neontrip.de'
      and s.conversation_id = pending.conversation_id
      and s.sent_at >= pending.created_at - interval '30 seconds'
      and s.sent_at < coalesce(pending.next_draft_at - interval '5 seconds', 'infinity'::timestamptz)
      and s.response_body_text <> ''
      and s.matched_source_message_id is null
      and not exists (
        select 1
        from public.email_agent_feedback f
        where f.sent_message_id = s.graph_message_id
      )
    order by
      (
        lower(coalesce(pending.from_email, '')) = any(s.recipient_emails)
      ) desc,
      s.sent_at asc
    limit 1
  ) sent on true
  order by pending.created_at asc
  limit greatest(1, least(coalesce(p_limit, 40), 100));
$function$;

create or replace function public.record_email_agent_feedback_from_index_v1(
  p_sent_index_id bigint,
  p_source_message_id text,
  p_conversation_id text,
  p_draft_id text,
  p_sent_message_id text,
  p_sent_internet_message_id text,
  p_draft_body_hash text,
  p_sent_body_hash text,
  p_sent_body_text text,
  p_edit_ratio numeric,
  p_edit_summary jsonb,
  p_edit_labels text[],
  p_change_profile jsonb,
  p_review_priority text
)
returns jsonb
language plpgsql
set search_path = public
as $function$
declare
  indexed_row public.email_agent_sent_index%rowtype;
  feedback_result jsonb;
  feedback_id_value bigint;
begin
  select *
  into indexed_row
  from public.email_agent_sent_index
  where id = p_sent_index_id
  for update;

  if not found then
    raise exception 'sent index row was not found';
  end if;
  if indexed_row.graph_message_id <> p_sent_message_id then
    raise exception 'sent message does not match sent index row';
  end if;
  if indexed_row.matched_source_message_id is not null
    and indexed_row.matched_source_message_id <> p_source_message_id then
    raise exception 'sent message is already matched to another source message';
  end if;

  feedback_result := public.record_email_agent_feedback_v2(
    p_source_message_id,
    p_conversation_id,
    p_draft_id,
    p_sent_message_id,
    p_sent_internet_message_id,
    p_draft_body_hash,
    p_sent_body_hash,
    p_sent_body_text,
    p_edit_ratio,
    p_edit_summary,
    p_edit_labels,
    p_change_profile,
    p_review_priority
  );

  feedback_id_value := nullif(feedback_result->>'feedback_id', '')::bigint;

  update public.email_agent_sent_index
  set matched_source_message_id = p_source_message_id,
      matched_feedback_id = feedback_id_value,
      matched_at = now(),
      last_seen_at = now()
  where id = p_sent_index_id;

  return feedback_result || jsonb_build_object(
    'sent_index_id', p_sent_index_id,
    'index_matched', true
  );
end;
$function$;

revoke all on function public.begin_email_agent_sent_sync_v1(text, text)
  from public, anon, authenticated;
revoke all on function public.record_email_agent_sent_sync_result_v1(
  text, text, text, integer, integer, text, text, jsonb, text, text, boolean
) from public, anon, authenticated;
revoke all on function public.get_email_agent_feedback_candidates_v1(integer)
  from public, anon, authenticated;
revoke all on function public.record_email_agent_feedback_from_index_v1(
  bigint, text, text, text, text, text, text, text, text, numeric, jsonb, text[], jsonb, text
) from public, anon, authenticated;

grant execute on function public.begin_email_agent_sent_sync_v1(text, text)
  to service_role;
grant execute on function public.record_email_agent_sent_sync_result_v1(
  text, text, text, integer, integer, text, text, jsonb, text, text, boolean
) to service_role;
grant execute on function public.get_email_agent_feedback_candidates_v1(integer)
  to service_role;
grant execute on function public.record_email_agent_feedback_from_index_v1(
  bigint, text, text, text, text, text, text, text, text, numeric, jsonb, text[], jsonb, text
) to service_role;

comment on table public.email_agent_sent_index is
  'Internal-only sanitized index of Sent Items used to match human replies to AI drafts without per-conversation Graph polling.';
comment on table public.email_agent_mail_sync_state is
  'Durable Microsoft Graph delta cursor, lease and backoff state for the AI email feedback collector.';
comment on function public.get_email_agent_feedback_candidates_v1(integer) is
  'Returns deterministic draft/sent candidate pairs from Postgres. It performs no Outlook calls and sends no customer communication.';
